project_id = "be-tv"

[auth]
site_url = "https://billieilishtv.site"
additional_redirect_urls = [
  "https://billieilishtv.site/pt-br/reset-password",
  "https://billieilishtv.site/en-us/reset-password",
  "https://billieilishtv.site/es/reset-password",
  "http://localhost:3000/pt-br/reset-password",
  "http://localhost:3000/en-us/reset-password",
  "http://localhost:3000/es/reset-password"
]

[auth.email.template.recovery]
subject = "Redefinir senha / Reset password / Restablecer contraseña"
content_path = "./supabase/templates/recovery.html"
