-- Remote history marker. The deployed translation worker preserves the official Hit Me Hard and Soft title.
-- Intentionally contains no SQL: it records an immutable migration that is already
-- present in the linked production database and prevents local/remote history drift.
