import "jsr:@supabase/functions-js@2.4.4/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";

const SITE="https://billieilishtv.site";
const ALLOWED_SITE_ORIGINS=new Set([SITE,"https://www.billieilishtv.site","https://be-bralis.vercel.app"]);
const PUBLIC=new Set(["contents","featured","movies","notifications","ongs","sections","series","videos"]);
const PUBLIC_SETTINGS=new Set(["site","billie-eilish","ong"]);
const TARGET:Record<string,string>={"en-us":"en",es:"es",fr:"fr"};
const FIELDS=["title","name","description","subtitle","body","summary","buttonLabel","buttonText","actionLabel","ctaLabel","label","text","manualBio","kicker","footerText","sectionName","siteName"];
const DURATIONS=["duration","runtime","videoDuration"];
const MUSIC_VIDEO_ID="18db9515-179c-4bad-9646-1fcda63df14a";
const MUSIC_VIDEO_NAMES=new Set(["videoclipes","videoclips","music videos","music video","videos musicais","vídeos musicais","videos musicales","vídeos musicales","vidéos musicales","vidéos musicaux"]);
const REV="20260810-music-album-lock-v4";
const PROVIDER="google-web-natural-v4";
const BASE_KEEP=[
  "WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?","HIT ME HARD AND SOFT","Happier Than Ever","dont smile at me","Guitar Songs",
  "all the good girls go to hell","bad guy","Bellyache","BIRDS OF A FEATHER","Bored","bury a friend","CHIHIRO","everything i wanted","Guess","hostage","idontwannabeyouanymore","Lo Vas A Olvidar","Lost Cause","lovely","LUNCH","Male Fantasy","my future","NDA","Never Felt So Alone","No Time To Die","ocean eyes","Therefore I Am","watch","What Was I Made For?","when the party's over","xanny","you should see me in a crown","Your Power","THE GREATEST","SKINNY","WILDFLOWER","L'AMOUR DE MA VIE","Billie Bossa Nova","Getting Older","TV","bitches broken hearts","listen before i go","come out and play","One Less Lonely Girl","Have Yourself A Merry Little Christmas",
  "Billie Eilish TV","Billie Eilish","FINNEAS","Prime Video","Apple TV","Paramount+","Disney+","Twitter / X","Discord","Google","Instagram","TikTok","Spotify","YouTube","Stripe","Supabase","BETV","DMCA","LGPD","HTTPS","BRL","USD","BE"
].sort((a,b)=>b.length-a.length);
let musicCatalogCache:string[]|null=null;
let musicCatalogCachedAt=0;
function addCatalogTerm(target:Set<string>,value:unknown){const term=text(value,300);if(term&&term.length>1)target.add(term);}
async function musicCatalogTerms(admin:any){
  const now=Date.now();
  if(musicCatalogCache&&now-musicCatalogCachedAt<300000)return musicCatalogCache;
  const terms=new Set<string>(BASE_KEEP);
  try{
    const {data,error}=await admin.from("content_items").select("collection,data").in("collection",["news","videos"]).limit(1000);
    if(error)throw error;
    for(const row of data||[]){
      const collection=text(row?.collection,40).toLowerCase();
      const payload=row?.data&&typeof row.data==="object"?row.data:{};
      if(collection==="news"){
        const tracks=Array.isArray(payload.tracks)?payload.tracks:[];
        const type=text(payload.type,50).toLowerCase();
        const looksMusical=tracks.length>0||/álbum|album|single|ep\b/.test(type);
        if(!looksMusical)continue;
        addCatalogTerm(terms,payload.title);
        addCatalogTerm(terms,payload.name);
        for(const track of tracks)addCatalogTerm(terms,track?.title||track?.name);
      }else if(collection==="videos"){
        const sectionId=text(payload.sectionId,120);
        const sectionName=text(payload.sectionName||payload.sourceSectionTitle,160).toLowerCase();
        if(sectionId===MUSIC_VIDEO_ID||MUSIC_VIDEO_NAMES.has(sectionName)){
          addCatalogTerm(terms,payload.title);
          addCatalogTerm(terms,payload.name);
        }
      }
    }
  }catch(error){console.warn("Music catalog protection fallback",text((error as Error)?.message,160));}
  musicCatalogCache=Array.from(terms).sort((a,b)=>b.length-a.length);
  musicCatalogCachedAt=now;
  return musicCatalogCache;
}
const GJSON="https://translate.googleapis.com/translate_a/single";
const GMOBILE="https://translate.google.com/m";
const text=(v:unknown,n=8000)=>String(v??"").trim().slice(0,n);
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));

function originOk(origin:string){if(!origin)return true;if(ALLOWED_SITE_ORIGINS.has(origin))return true;try{const u=new URL(origin);return ["localhost","127.0.0.1"].includes(u.hostname)&&["http:","https:"].includes(u.protocol)}catch{return false}}
function cors(req:Request):HeadersInit{const o=req.headers.get("origin")||SITE;return {"Access-Control-Allow-Origin":originOk(o)?o:SITE,"Access-Control-Allow-Headers":"authorization,x-client-info,apikey,content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Access-Control-Max-Age":"86400","Vary":"Origin"}}
function reply(req:Request,status:number,payload:Record<string,unknown>){return new Response(JSON.stringify(payload),{status,headers:{...cors(req),"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","X-Content-Type-Options":"nosniff"}})}
function esc(v:string){return v.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}
function decode(v:string){return v.replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCodePoint(parseInt(n,16))).replace(/&nbsp;/gi," ").replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&amp;/gi,"&")}
function htmlResult(html:string){for(const re of [/<div[^>]*class=["'][^"']*\bresult-container\b[^"']*["'][^>]*>([\s\S]*?)<\/div>/i,/<div[^>]*class=["'][^"']*\bt0\b[^"']*["'][^>]*>([\s\S]*?)<\/div>/i]){const m=html.match(re);if(m){const z=decode(m[1].replace(/<br\s*\/?\s*>/gi,"\n").replace(/<[^>]+>/g,"")).trim();if(z)return z}}return ""}
function protect(input:string,protectedTerms:string[]=BASE_KEEP){const vals:string[]=[];const hold=(v:string)=>`[[[${vals.push(v)-1}]]]`;let s=input;for(const re of [/⟦\s*BETV\d+_\d+\s*⟧/gi,/https?:\/\/[^\s<>()]+/gi,/[\w.+-]+@[\w.-]+\.[a-z]{2,}/gi,/\{[a-zA-Z0-9_]+\}/g,/\$\{[^}]+\}/g,/@[a-zA-Z0-9_.-]+/g,/#(?:[a-zA-Z0-9_.-]+)/g,/\bbe_[a-z0-9_]+\b/gi])s=s.replace(re,m=>hold(m));for(const term of protectedTerms){const re=new RegExp(`(^|[^\\p{L}\\p{N}])(${esc(term)})(?=$|[^\\p{L}\\p{N}])`,"giu");s=s.replace(re,(_m,p,m)=>`${p}${hold(m)}`)}return {value:s,restore:(v:string)=>v.replace(/\[\s*\[\s*\[\s*(\d+)\s*\]\s*\]\s*\]/g,(_m,i)=>vals[Number(i)]??_m)}}
function natural(v:string,target:string){if(target==="es")return v.replace(/\bUsted puede\b/g,"Puedes").replace(/\busted puede\b/g,"puedes").replace(/\bUsted debe\b/g,"Debes").replace(/\busted debe\b/g,"debes").replace(/\bUsted tiene\b/g,"Tienes").replace(/\busted tiene\b/g,"tienes").replace(/\bUsted está\b/g,"Estás").replace(/\busted está\b/g,"estás").replace(/\bSeleccione\b/g,"Selecciona").replace(/\bseleccione\b/g,"selecciona").replace(/\bElija\b/g,"Elige").replace(/\belija\b/g,"elige").replace(/\bIntroduzca\b/g,"Ingresa").replace(/\bintroduzca\b/g,"ingresa").replace(/\bIngrese\b/g,"Ingresa").replace(/\bingrese\b/g,"ingresa").replace(/\bCompruebe\b/g,"Revisa").replace(/\bcompruebe\b/g,"revisa").replace(/\bVerifique\b/g,"Revisa").replace(/\bverifique\b/g,"revisa").replace(/\bHaga clic\b/g,"Haz clic").replace(/\bhaga clic\b/g,"haz clic").replace(/\bvídeo\b/gi,"video").replace(/\bvídeos\b/gi,"videos").replace(/\bordenador\b/gi,"computadora").replace(/\bmóvil\b/gi,"celular").replace(/\bimporte\b/gi,"monto").replace(/\bimportes\b/gi,"montos").replace(/\bcostes\b/gi,"costos");if(target==="fr")return v.replace(/\bVeuillez\s+/g,"").replace(/\bveuillez\s+/g,"").replace(/\bVous pouvez\b/g,"Tu peux").replace(/\bvous pouvez\b/g,"tu peux").replace(/\bVous devez\b/g,"Tu dois").replace(/\bvous devez\b/g,"tu dois").replace(/\bChoisissez\b/g,"Choisis").replace(/\bchoisissez\b/g,"choisis").replace(/\bSélectionnez\b/g,"Sélectionne").replace(/\bsélectionnez\b/g,"sélectionne");return v}
async function translateChunk(input:string,target:string,protectedTerms:string[]=BASE_KEEP){if(!input.trim())return input;const p=protect(input,protectedTerms),source=p.value;try{const u=new URL(GJSON);for(const [k,v] of [["client","gtx"],["sl","auto"],["tl",target],["dt","t"],["q",source]])u.searchParams.set(k,v);const r=await fetch(u,{signal:AbortSignal.timeout(15000),headers:{Accept:"application/json","User-Agent":"Mozilla/5.0 BETV-Translator/3.0"}});if(r.ok){const j=await r.json();if(Array.isArray(j?.[0])){const z=j[0].map((x:unknown)=>Array.isArray(x)?String(x[0]||""):"").join("").trim();if(z)return p.restore(z)}}}catch{}const u=new URL(GMOBILE);u.searchParams.set("sl","auto");u.searchParams.set("tl",target);u.searchParams.set("hl",target);u.searchParams.set("q",source);for(let i=1;i<=3;i++){try{const r=await fetch(u,{signal:AbortSignal.timeout(15000),headers:{Accept:"text/html,application/xhtml+xml","User-Agent":"Mozilla/5.0 BETV-Translator/3.0"}});if(!r.ok)throw new Error(`http_${r.status}`);const z=htmlResult(await r.text());if(z)return p.restore(z);throw new Error("missing")}catch(e){if(i===3)throw e;await sleep(350*i)}}throw new Error("translation_failed")}
function chunks(v:string){const a:string[]=[];let s=v;while(s.length>1700){const x=s.slice(0,1701),cut=Math.max(x.lastIndexOf("\n"),x.lastIndexOf(". "),x.lastIndexOf(" "));const n=cut>900?cut+1:1700;a.push(s.slice(0,n));s=s.slice(n)}if(s)a.push(s);return a}
async function translateValues(values:string[],target:string,protectedTerms:string[]=BASE_KEEP){if(!values.length)return [];const pieces:{i:number,p:number,s:string,m:string}[]=[];values.forEach((v,i)=>chunks(v).forEach((s,p)=>pieces.push({i,p,s,m:`⟦BETV${i}_${p}⟧`})));const result=new Array<string>(values.length).fill("");let group:typeof pieces=[],size=0;const groups:(typeof pieces)[]=[];for(const x of pieces){const n=x.m.length+x.s.length+3;if(group.length&&size+n>1650){groups.push(group);group=[];size=0}group.push(x);size+=n}if(group.length)groups.push(group);const map=new Map<string,string>();for(const g of groups){const joined=g.map(x=>`${x.m}\n${x.s}`).join("\n");const tr=await translateChunk(joined,target,protectedTerms);const mm=Array.from(tr.matchAll(/⟦\s*BETV(\d+)_(\d+)\s*⟧/gi));if(mm.length===g.length)mm.forEach((m,k)=>{const st=(m.index||0)+m[0].length,en=k+1<mm.length?(mm[k+1].index||tr.length):tr.length;map.set(`${m[1]}:${m[2]}`,tr.slice(st,en).trim())});else for(const x of g){map.set(`${x.i}:${x.p}`,await translateChunk(x.s,target,protectedTerms));await sleep(40)}await sleep(60)}values.forEach((_v,i)=>{result[i]=natural(pieces.filter(x=>x.i===i).sort((a,b)=>a.p-b.p).map(x=>map.get(`${x.i}:${x.p}`)||x.s).join("").trim(),target)});return result}
function preserveTitle(collection:string,data:Record<string,unknown>,locale:string){if(!["es","fr"].includes(locale))return false;if(data.preserveTitle===true||text(data.preserveTitle,10).toLowerCase()==="true")return true;if(["albums","albuns","álbuns"].includes(collection))return true;if(collection!=="videos")return false;const n=text(data.sectionName||data.sourceSectionTitle,160).toLowerCase();return text(data.sectionId,120)===MUSIC_VIDEO_ID||MUSIC_VIDEO_NAMES.has(n)}
function active(v:unknown){return v!==false&&text(v||"true").toLowerCase()!=="false"}
function duration(v:unknown,locale:string){const raw=text(v,120);if(!raw)return raw;const h=raw.match(/(\d+)\s*(?:h|hr|hrs|hora|horas)\b/i),m=raw.match(/(\d+)\s*(?:m|min|mins|minuto|minutos)\b/i);if(!h&&!m)return raw;return [h?(locale==="en-us"?`${Number(h[1])} hr`:`${Number(h[1])} h`):"",m?`${Number(m[1])} min`:""].filter(Boolean).join(" ")}
function signature(data:Record<string,unknown>){const src:Record<string,unknown>={};for(const f of [...FIELDS,...DURATIONS])if(Object.prototype.hasOwnProperty.call(data,f))src[f]=data[f];const s=JSON.stringify(src);let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return `src-${(h>>>0).toString(16)}`}

Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(req)});if(req.method!=="POST")return reply(req,405,{error:"Método não permitido."});const origin=req.headers.get("origin")||"";if(!originOk(origin))return reply(req,403,{error:"Origem não permitida."});let body:Record<string,unknown>;try{body=await req.json()}catch{return reply(req,400,{error:"Dados inválidos."})}
const mode=text(body.mode,20).toLowerCase();if(mode==="texts"){if(!origin)return reply(req,403,{error:"Origem necessária."});const locale=text(body.locale,10).toLowerCase(),target=TARGET[locale];const texts=Array.from(new Set((Array.isArray(body.texts)?body.texts:[]).map(v=>text(v,1800)).filter(v=>v&&/\p{L}/u.test(v)))).slice(0,60);if(!target||!texts.length||texts.reduce((s,v)=>s+v.length,0)>9000)return reply(req,400,{error:"Solicitação de tradução inválida."});try{let protectedTerms=BASE_KEEP;const u=Deno.env.get("SUPABASE_URL")||"",svc=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";if(u&&svc){const catalogAdmin=createClient(u,svc,{auth:{persistSession:false,autoRefreshToken:false}});protectedTerms=await musicCatalogTerms(catalogAdmin);}return reply(req,200,{locale,style:"informal-native",translations:await translateValues(texts,target,protectedTerms),provider:PROVIDER,revision:REV})}catch(e){console.error("UI translation failed",text((e as Error)?.message,160));return reply(req,503,{error:"Tradução temporariamente indisponível."})}}
const collection=text(body.collection,40).toLowerCase();const ids=Array.from(new Set((Array.isArray(body.ids)?body.ids:[]).map(v=>text(v,120)).filter(Boolean))).slice(0,50);const locales=Array.from(new Set((Array.isArray(body.locales)?body.locales:[]).map(v=>text(v,10).toLowerCase()).filter(v=>TARGET[v])));const force=body.force===true;if((collection!=="settings"&&!PUBLIC.has(collection))||!ids.length||!locales.length)return reply(req,400,{error:"Solicitação de tradução inválida."});
const url=Deno.env.get("SUPABASE_URL")||"",anon=Deno.env.get("SUPABASE_ANON_KEY")||"",service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";if(!url||!anon||!service)return reply(req,503,{error:"Servidor de tradução incompleto."});const auth=req.headers.get("authorization")||"";const user=createClient(url,anon,{global:{headers:auth?{Authorization:auth}:{}},auth:{persistSession:false,autoRefreshToken:false}}),admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});const protectedTerms=await musicCatalogTerms(admin);let isAdmin=false;if(auth.startsWith("Bearer ")){const {data:u}=await user.auth.getUser().catch(()=>({data:{user:null}}));if(u?.user){const {data}=await user.rpc("is_admin").catch(()=>({data:false}));isAdmin=data===true}}if(!isAdmin){const publicSettings=collection==="settings"&&ids.every(id=>PUBLIC_SETTINGS.has(id));if(force||(!PUBLIC.has(collection)&&!publicSettings))return reply(req,403,{error:"Acesso administrativo necessário."})}
const table=collection==="settings"?"site_settings":"content_items";let q=admin.from(table).select("id,data,created_at,updated_at").in("id",ids);if(collection!=="settings")q=q.eq("collection",collection);const {data:loaded,error:loadError}=await q;if(loadError)return reply(req,500,{error:"Não foi possível carregar o conteúdo."});const rows=(loaded||[]).filter((r:any)=>isAdmin||collection==="settings"||active(r.data?.active));let total=0;const records:Record<string,unknown>[]=[];try{for(const row of rows as any[]){const data={...(row.data||{})},translations={...(data.translations||{})},sig=signature(data);for(const locale of locales){const keep=preserveTitle(collection,data,locale),existing=translations[locale];const complete=keep||(!Object.prototype.hasOwnProperty.call(data,"title")||Object.prototype.hasOwnProperty.call(existing||{},"title"))&&(!Object.prototype.hasOwnProperty.call(data,"name")||Object.prototype.hasOwnProperty.call(existing||{},"name"));const revisionOk=!(["es","fr"].includes(locale))||String(existing?.revision||"")===REV;if(!force&&existing&&existing.sourceUpdatedAt===sig&&complete&&revisionOk){const cached={...existing};if(keep){delete cached.title;delete cached.name;translations[locale]=cached}records.push({id:row.id,locale,translation:cached,cached:true});continue}const fields=FIELDS.filter(f=>!(keep&&(f==="title"||f==="name"))).filter(f=>typeof data[f]==="string"&&text(data[f])&&!/^https?:\/\//i.test(text(data[f])));total+=fields.reduce((s,f)=>s+text(data[f]).length,0);if(total>30000)return reply(req,413,{error:"Conteúdo excede o limite por solicitação."});const vals=await translateValues(fields.map(f=>text(data[f])),TARGET[locale],protectedTerms);const tr:Record<string,unknown>={sourceUpdatedAt:sig,translatedAt:new Date().toISOString(),style:"informal-native",provider:PROVIDER,revision:REV};fields.forEach((f,i)=>tr[f]=vals[i]||data[f]);DURATIONS.forEach(f=>{if(typeof data[f]==="string"&&text(data[f]))tr[f]=duration(data[f],locale)});translations[locale]=tr;records.push({id:row.id,locale,translation:tr,cached:false})}data.translations=translations;const {error}=await admin.from(table).update({data}).eq("id",row.id);if(error)throw new Error(`save_${error.code}`)}return reply(req,200,{records,translatedRecords:rows.length,locales,style:"informal-native",provider:PROVIDER,revision:REV})}catch(e){console.error("Translation failed",text((e as Error)?.message,160));return reply(req,503,{error:"A tradução automática está temporariamente indisponível."})}});
